#!/usr/bin/env bash

# Running ./setup creates links in the
# qmk_firmware directory keymaps or keyboards
# folders so that we can keep custom keymaps/boards
# under separate version control, while pulling changes
# from QMK itself.
#
# Actual keymap for 3x5 ferris sweep
# qmk compile -kb ferris/sweep -km ernierasta

MY_HOME=`echo $HOME`
QMK_HOME="$MY_HOME/qmk_firmware"

# Gets the full path to this keymaps repo's directory
REPO_DIR="$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"


function symlink_ferris_sweep_custom_keymap() {
  local source_keymap="$REPO_DIR/ernierasta"
  local symlink_destination="$QMK_HOME/keyboards/ferris/keymaps/ernierasta"

  if [ ! -d "$symlink_destination" ]; then
    echo "Symlinking Ferris Sweep ernierasta keymap"
    ln -s "$source_keymap" "$symlink_destination"
  else
    echo "Keymap already in place, nothing to do"
  fi
  echo "Build:"
  echo "qmk compile -kb ferris/sweep -km ernierasta"
}

symlink_ferris_sweep_custom_keymap
